// ─── generators.js ──────────────────────────────────────────────────────────
// Generates scaffolding file content from wizard form data.
// Each function returns a string (the file content).

// All sdd-kit static files, bundled at build time by scripts/bundle-kit.js
import kitFiles from '../data/kit-files.json' with { type: 'json' };

const today = () => new Date().toISOString().split('T')[0];

// ─── context/project.md ─────────────────────────────────────────────────────
export function generateProjectMd(data) {
  const { project } = data;
  const personaRows = (project.personas || [])
    .filter(p => p.name)
    .map(p => `| ${p.name} | ${p.description || ''} | ${p.goals || ''} | ${p.painPoints || ''} |`)
    .join('\n');

  const personaTable = personaRows
    ? `| Persona | Description | Primary Goals | Pain Points |\n|---|---|---|---|\n${personaRows}`
    : `| Persona | Description | Primary Goals | Pain Points |\n|---|---|---|---|\n| [Add persona] | [Who they are] | [What they want] | [What frustrates them] |`;

  return `# Project Overview

<!-- 
  GENERATED BY: SpecDD Starter Kit Setup Wizard
  Last updated: ${today()}
  
  This is the top-level project context. Always included when AI generates specs or code.
-->

---

## Status
\`DRAFT\` — Review and update as the project evolves.

---

## Project Identity

**Name:** ${project.name || '[PROJECT_NAME]'}

**One-sentence description:**  
${project.description || '[What does this project do and for whom?]'}

**Problem statement:**  
${project.problemStatement || '[What real-world problem does this project solve? Why does it need to exist?]'}

---

## Users & Personas

${personaTable}

---

## Success Criteria

What does "successful" look like for this project?

- **User outcome:** ${project.userOutcome || '[e.g., Users can complete X in < Y seconds]'}
- **Business outcome:** ${project.businessOutcome || '[e.g., Reduce support tickets by X%]'}
- **Technical outcome:** [e.g., System handles X concurrent users with < Y ms latency]
- **Quality outcome:** [e.g., Zero critical bug reports in first 30 days]

---

## Key Constraints

Business constraints:
${project.businessConstraints ? project.businessConstraints.split('\n').map(c => `- ${c}`).join('\n') : '- [e.g., Must launch by Q3 2026]\n- [e.g., Must comply with GDPR]'}

Technical constraints:
${project.technicalConstraints ? project.technicalConstraints.split('\n').map(c => `- ${c}`).join('\n') : '- [e.g., Must integrate with existing SSO provider]\n- [e.g., Azure only — no new cloud providers]'}

---

## AI Agent Context

This project uses **${formatAgent(data.agent?.primary)}** as the primary AI coding agent${data.agent?.model ? ` with **${data.agent.model}** as the default model` : ''}.
`;
}

// ─── Lookup helpers ─────────────────────────────────────────────────────────
const DEVOPS_ROLE = {
  Jira: 'Project tracking, sprints, backlog',
  'GitHub Actions': 'CI/CD pipelines',
  'GitHub Projects': 'Board, backlog, roadmap',
  'GitLab CI/CD': 'Pipelines and issues',
  ServiceNow: 'ITSM, change management',
  Linear: 'Engineering project management',
};

function getDevopsRole(t) {
  if (t.includes('ADO') || t.includes('Azure DevOps')) return 'Boards, Pipelines, Repos, Artifacts';
  return DEVOPS_ROLE[t] || 'DevOps tooling';
}

function generateToolingContext(techStack) {
  if (!techStack?.devops?.length && !techStack?.sourceControl) return '';
  const scLine = techStack.sourceControl
    ? `**Source control:** ${techStack.sourceControl}`
    : '';
  const devopsBullets = (techStack.devops || []).map(t => `- ${t}`).join('\n');
  const devopsList = techStack.devops?.length
    ? `**Project tracking / CI:**\n${devopsBullets}`
    : '';
  const adoLine = techStack.devops?.includes('Azure DevOps (ADO)')
    ? '**Azure DevOps:** Before every pipeline, CI/CD, or work-item task, read `.github/instructions/azure-devops-pipelines.instructions.md`. Branch names follow `feature/[id]-short-desc`. Pipelines are YAML (`azure-pipelines.yml` or `.azure-pipelines/`). Work item hierarchy: Epics → Features → Stories → Tasks.'
    : '';
  const ghaLine = techStack.devops?.includes('GitHub Actions')
    ? '**GitHub Actions:** Before every CI/CD workflow task, read `.github/instructions/github-actions.instructions.md`. Workflow files go in `.github/workflows/`. Use OIDC for cloud auth, pin action versions to SHA or major tag, and set `permissions: contents: read` by default.'
    : '';
  const jiraLine = techStack.devops?.includes('Jira')
    ? '**Jira:** Prefix commit messages and branch names with the Jira issue key (e.g. `PROJ-123: ...`). Work item hierarchy: Epics → Stories → Sub-tasks.'
    : '';
  const lines = [scLine, devopsList, adoLine, ghaLine, jiraLine].filter(Boolean).join('\n');
  return `\n## Tooling & DevOps Context\n\n${lines}\n`;
}

function buildSwaggerSection(techStack) {
  if (!techStack.useSwagger) return '';
  return `
---

## API Documentation — OpenAPI / Swagger

| Tool | Version | Purpose |
|---|---|---|
| OpenAPI Specification | 3.1 | API contract standard |
| Swagger UI | Latest | Interactive API explorer (dev/staging only) |
| Framework library | (see below) | Code-first doc generation |

**Framework setup:**
- **ASP.NET Core (.NET 9+):** Built-in \`Microsoft.AspNetCore.OpenApi\` + Swagger UI via \`Swashbuckle.AspNetCore.SwaggerUI\`
- **ASP.NET Core (.NET 8):** \`Swashbuckle.AspNetCore\` — \`AddSwaggerGen()\` + \`UseSwaggerUI()\`
- **FastAPI:** Built-in, configure \`docs_url=None\` in production
- **NestJS:** \`@nestjs/swagger\` — \`SwaggerModule.setup()\`
- **Express.js:** \`swagger-jsdoc\` + \`swagger-ui-express\`
- **Spring Boot:** \`springdoc-openapi-starter-webmvc-ui\` 2.x

**Mandatory rules:**
- Every public endpoint MUST have an OpenAPI annotation with \`operationId\`, parameters, and all response codes
- Swagger UI and \`/openapi.json\` endpoint MUST be disabled in production (environment guard)
- All APIs MUST implement \`/health\` and \`/health/ready\` endpoints
- Error responses MUST use a consistent \`ErrorResponse\` schema — never raw strings
- \`operationId\` follows \`verbNoun\` convention: \`getUser\`, \`listOrders\`, \`createPayment\`
- Datetime fields use ISO 8601 (\`date-time\` format); IDs document integer or UUID type

Full rules and code examples in: \`.github/instructions/swagger-api-docs.instructions.md\``;
}

// ─── context/tech-stack.md ───────────────────────────────────────────────────
export function generateTechStackMd(data) {
  const { techStack } = data;

  const langRows = (techStack.languages || [])
    .map(lang => `| ${lang} | Latest stable | All application code |`)
    .join('\n') || '| [Language] | [Version] | [Usage] |';

  const feSuffix = techStack.frontendOther ? ` (${techStack.frontendOther})` : '';
  const frontendRow = techStack.frontend && techStack.frontend !== 'none'
    ? `| ${techStack.frontend}${feSuffix} | Latest | UI framework |`
    : '| None |  |  |';

  const beSuffix = techStack.backendOther ? ` (${techStack.backendOther})` : '';
  const backendRow = techStack.backend && techStack.backend !== 'none'
    ? `| ${techStack.backend}${beSuffix} | Latest | Web framework |`
    : '| None |  |  |';

  const testingRows = (techStack.testing || [])
    .map(t => `| ${t} | Latest | Tests |`)
    .join('\n') || '| [Test framework] | [Version] | [Scope] |';

  const dbRow = techStack.database && techStack.database !== 'none'
    ? `| ${techStack.database} | Latest | Primary data store |`
    : '';

  const infraRows = (techStack.infrastructure || [])
    .filter(i => i !== 'none')
    .map(i => `| ${i} | — | Infrastructure |`)
    .join('\n') || '| [Service] | [Provider] | [Purpose] |';

  const swaggerSection = buildSwaggerSection(techStack);

  const sourceControlRow = techStack.sourceControl && techStack.sourceControl !== 'other'
    ? `| ${techStack.sourceControl} | — | Source control |`
    : '';

  const devopsRows = (techStack.devops || [])
    .map(t => `| ${t} | — | ${getDevopsRole(t)} |`)
    .join('\n');

  const adoConventions = techStack.devops?.includes('Azure DevOps (ADO)')
    ? '**Azure DevOps conventions:**\n'
      + '- Work items: Epics → Features → User Stories → Tasks\n'
      + '- Branch strategy: `main` (protected) + `feature/[task-id]-[short-desc]` + `hotfix/`\n'
      + '- Pull requests require at least 1 reviewer and all CI checks to pass before merge\n'
      + '- Pipelines defined as YAML in `.azure-pipelines/` or `azure-pipelines.yml`\n'
      + '- Environments: `dev`, `staging`, `production` — each requires approval gate before deploy to prod\n'
    : '';
  const jiraConventions = techStack.devops?.includes('Jira')
    ? '**Jira conventions:**\n'
      + '- Issue hierarchy: Epics → Stories → Sub-tasks\n'
      + '- Branches should reference Jira issue key: `feature/PROJ-123-short-desc`\n'
      + '- Commit messages should prefix with issue key: `PROJ-123: short description`\n'
      + '- Status flow: To Do → In Progress → In Review → Done\n'
    : '';
  const ghaConventions = techStack.devops?.includes('GitHub Actions')
    ? '**GitHub Actions conventions:**\n'
      + '- Workflow files in `.github/workflows/`\n'
      + '- Use reusable workflows for shared CI steps\n'
      + '- Require passing CI checks before PR merge (branch protection rules)\n'
    : '';

  const toolingSection = (sourceControlRow || devopsRows) ? `
---

## Tooling & DevOps

| Tool | Version | Purpose |
|---|---|---|
${[sourceControlRow, devopsRows].filter(Boolean).join('\n')}

${adoConventions}${jiraConventions}${ghaConventions}` : '';

  const motifSection = techStack.useMotif ? `
---

## EY Design System — Motif

| Package | Version | Purpose |
|---|---|---|
| \`@ey-xd/motif-components\` | 11.x | Web Components core |
| \`@ey-xd/motif-wc-react\` | 11.x | React wrappers |
| \`@ey-xd/motif-icon\` | Latest | Iconoir icon library |

**Registry:** \`https://eyctpeu.jfrog.io/artifactory/api/npm/ey-npm/\`

**Mandatory rules:**
- Use Motif design tokens for all colours and spacing — never hard-code values
- Use Motif component library before building any custom UI
- Apply Motif typography scale classes (\`motif-heading-4\`, \`motif-body-1\`, etc.)
- Support both \`data-motif-theme="light"\` and \`dark\`
- WCAG AA accessibility compliance is required on every component
- Follow Figma → MCP \`get_design_context\` → Motif implementation workflow

Full rules in: \`.github/instructions/motif-design-system.instructions.md\`` : '';

  return `# Tech Stack
<!-- 
  GENERATED BY: SpecDD Starter Kit Setup Wizard
  Last updated: ${today()}
  
  AI coding agents reference this file for every code generation task.
  All implementation must use ONLY approved technologies unless explicitly approved otherwise.
-->

---

## Status
\`ACTIVE\` — Update when adding or deprecating a technology.

---

## Languages

| Language | Version | Usage |
|---|---|---|
${langRows}

---

## Core Frameworks & Libraries

### Frontend
| Library | Version | Purpose |
|---|---|---|
${frontendRow}

### Backend
| Library | Version | Purpose |
|---|---|---|
${backendRow}

---

## Testing

| Library | Version | Scope |
|---|---|---|
${testingRows}

---

## Data

| Store | Version | Purpose |
|---|---|---|
${dbRow || '| [Database] | [Version] | [Purpose] |'}

---

## Infrastructure & Platform

| Service | Version/Provider | Purpose |
|---|---|---|
${infraRows}

---

## Banned / Not Approved

- Do not introduce new dependencies without explicit team discussion
- Do not deviate from the above stack without updating this file

---

## Version Policy

- Prefer LTS / stable releases
- Pin major versions in \`package.json\` / \`requirements.txt\` / \`.csproj\`
- Security patches must be applied within 30 days of disclosure
${toolingSection}
${swaggerSection}
${motifSection}
`;
}

// ─── context/constitution.md ─────────────────────────────────────────────────
export function generateConstitutionMd(data) {
  const { constitution, governance, project } = data;

  const securityLines = (constitution.security || [])
    .map(s => `- [ ] **${s}:** Must be addressed in every release`)
    .join('\n') || '- [ ] **Security:** [Fill in security requirements]';

  const archStyle = constitution.architectureStyle
    ? constitution.architectureStyle.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ')
    : '[Architecture style]';

  const governanceNamespace = buildNamespace(governance, project);

  return `# Project Constitution

> **This file is auto-loaded as context for all AI coding sessions.**  
> All code generation, spec creation, and planning must comply with these principles.

<!-- 
  GOVERNANCE METADATA
  Level:        product  (Level 4 of 4)
  Namespace:    ${governanceNamespace}
  
  GENERATION METADATA
  Generated by: SpecDD Starter Kit Setup Wizard
  Last updated: ${today()}
  
  DO NOT MODIFY without explicit team approval and re-confirmation with AI agent.
  A lower governance level cannot override a higher one.
-->

---

## Status
\`ACTIVE\` — Approved and in effect.

---

## 1. Core Values & Quality Principles

- [ ] **Code Quality:** ${constitution.codeQuality || 'All code must be reviewed, linted, and tested before merge'}
- [ ] **Performance:** ${constitution.performance || 'Define performance targets for your use case'}
- [ ] **Reliability:** 99.9% monthly uptime target; automated rollback on failed deploys
${securityLines}

---

## 2. Architecture & Design Principles

- [ ] **Architecture Style:** ${archStyle}
- [ ] **Coupling:** Modules communicate only via defined interfaces, not internal APIs
- [ ] **New Components:** Any new module requires architecture review
- [ ] **Interface Design:** API-first; contracts defined before implementation

---

## 3. Testing Requirements

- [ ] **Minimum Coverage:** ${constitution.testCoverage || 80}% line coverage required for all modules
- [ ] **Test Types:** Unit tests required; integration and E2E tests for critical paths
- [ ] **Test Naming:** Tests must describe behavior, not implementation (\`should [do X] when [Y]\`)
- [ ] **No Broken Windows:** All tests must pass before merge; no skipped tests without documented reason

---

## 4. Security Non-Negotiables

${(constitution.security || []).length > 0
    ? (constitution.security || []).map(s => `- [ ] **${s}** compliance required`).join('\n')
    : '- [ ] OWASP Top 10 must be addressed in every release\n- [ ] No hardcoded credentials or secrets — use environment variables or secrets manager\n- [ ] Input validation on all public-facing endpoints'}
- [ ] Dependency vulnerability scanning on every CI run
- [ ] Zero known critical/high CVEs in production

---

## 5. AI Agent Rules

- The AI agent must not implement anything not specified in an approved spec
- The AI agent must not modify governance files (this file, governance/)
- The AI agent must ask before creating new files outside the approved project structure
- Every implementation task must reference a spec and plan

---

## 6. Definition of Done

A feature is "done" when:
1. All acceptance criteria from the spec are met and verified
2. Tests written and passing (>= ${constitution.testCoverage || 80}% coverage)
3. Code reviewed and approved
4. Docs updated if public API changed
5. No critical/high security findings introduced
${constitution.additionalRules ? `\n---\n\n## 7. Additional Non-Negotiables\n\n${constitution.additionalRules}` : ''}
`;
}

// ─── .github/copilot-instructions.md ──────────────────────────────────────────
export function generateCopilotInstructions(data) {
  const { project, agent } = data;
  const personaList = (project.personas || [])
    .filter(p => p.name)
    .map(p => p.name)
    .join(', ') || '[USER_PERSONAS]';

  const modelNote = agent?.model
    ? `\n> **Default model:** ${agent.model}\n`
    : '';

  return `# GitHub Copilot Workspace Instructions

<!-- 
  This file is automatically loaded as context for GitHub Copilot in this workspace.
  Generated by: SpecDD Starter Kit Setup Wizard (${today()})
-->

## Project Identity

**Project:** ${project.name || '[PROJECT_NAME]'}  
**Purpose:** ${project.description || '[ONE_SENTENCE_DESCRIPTION]'}  
**Primary Users:** ${personaList}
${modelNote}
---

## SpecDD Workflow Commands

**Governance setup** (run once per governance level, highest first):

| Command | Purpose |
|---|---|
| \`/sdd-blueprint\` | Generate BU-level reference architectures and standards (Level 2) |
| \`/sdd-domain-spec\` | Generate domain namespace spec and shared models (Level 3) |
| \`/sdd-constitution\` | Generate product governing principles (Level 4) |
| \`/sdd-context-map\` | Map bounded contexts and their relationships |

**Feature workflow** (run for each feature):

| Command | Purpose |
|---|---|
| \`/sdd-specify\` | Create a functional specification for a feature |
| \`/sdd-plan\` | Generate a technical implementation plan |
| \`/sdd-tasks\` | Break down spec + plan into actionable tasks |
| \`/sdd-implement\` | Execute implementation tasks one by one |

**Optional enhancement commands:**

| Command | Purpose |
|---|---|
| \`/sdd-clarify\` | Resolve ambiguities in a spec before planning |
| \`/sdd-checklist\` | Validate spec/plan quality |
| \`/sdd-analyze\` | Cross-check spec, plan, and tasks before implementing |
| \`/sdd-code-review\` | Comprehensive code review against spec, governance, and quality |
| \`/sdd-adr\` | Record an Architectural Decision |
| \`/sdd-spike\` | Run a time-boxed technical investigation |

---

## Agent Behavior

Behavior rules are defined in \`.github/instructions/agent-behavior.instructions.md\` and load automatically.

Governance loading order and Context references are in \`.github/instructions/governance.instructions.md\`.
${data.techStack?.useSwagger ? `
## API Documentation

This project uses **OpenAPI 3.1** for all backend API documentation. Before every backend task, read:
- \`.github/instructions/swagger-api-docs.instructions.md\` — setup, annotations, schema rules, security
- \`context/tech-stack.md\` — approved API doc tooling for this project

Key rules: every endpoint needs an annotation with \`operationId\`, all response codes documented, Swagger UI disabled in production.
` : ''}
${data.techStack?.useMotif ? `
## EY Design System

This project uses the **Motif Design System**. Before every UI task, read:
- \`.github/instructions/motif-design-system.instructions.md\` — design rules and token reference
- \`context/tech-stack.md\` — approved Motif packages and version

Key rules: use design tokens, use Motif components, WCAG AA required, support light/dark themes.
` : ''}
${data.techStack?.useA11y ? `
## Accessibility

This project requires **WCAG 2.2 Level AA** compliance. Before every UI task, read:
- \`.github/instructions/a11y.instructions.md\` — non-negotiables, ARIA rules, keyboard, focus, contrast

Key rules: prefer native HTML over ARIA, all interactive elements keyboard-operable, visible focus on all controls, no colour-only meaning, inclusive language in all user-facing text.
` : ''}
${(data.mcp?.tools || []).includes('sonarqube') ? `
## Code Quality — SonarQube

This project uses **SonarQube** for continuous static analysis. Before every coding task, read:
- \`.github/instructions/sonarqube.instructions.md\` — complexity rules, duplication, security hotspots, smells

Key rules: cognitive complexity ≤ 15 per function (refactor at > 10); no empty catch blocks; no hardcoded secrets; all Promises handled; no nested ternaries; no copy-pasted blocks. Every \`// NOSONAR\` suppression requires a justification comment.
` : ''}
${generateToolingContext(data.techStack)}
`;
}

// ─── .vscode/mcp.json ────────────────────────────────────────────────────────
export function generateMcpJson(data) {
  const { mcp } = data;
  const tools = mcp?.tools || [];
  const servers = {};

  if (tools.includes('github')) {
    servers['github'] = {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-github'],
      env: { GITHUB_PERSONAL_ACCESS_TOKEN: '${env:GITHUB_TOKEN}' }
    };
  }

  if (tools.includes('sonarqube')) {
    servers['sonarqube'] = {
      command: 'npx',
      args: ['-y', '@sonarsource/mcp-server-sonarqube'],
      env: {
        SONAR_TOKEN: '${env:SONAR_TOKEN}',
        SONAR_HOST_URL: 'https://sonarcloud.io'
      }
    };
  }

  if (tools.includes('context7')) {
    servers['context7'] = {
      command: 'npx',
      args: ['-y', '@upstash/context7-mcp@latest'],
    };
  }

  if (tools.includes('postgres')) {
    servers['postgresql'] = {
      command: 'npx',
      args: ['-y', '@modelcontextprotocol/server-postgres', '${env:DATABASE_URL}']
    };
  }

  if (Object.keys(servers).length === 0) return null;

  return JSON.stringify({ servers }, null, 2);
}

// ─── shouldSkipFile ──────────────────────────────────────────────────────────
function shouldSkipFile(path, formData) {
  const { governance, techStack, mcp } = formData;
  const levels  = governance?.levels        || ['product'];
  const devops  = techStack?.devops         || [];
  const fe      = techStack?.frontend       || '';
  const be      = techStack?.backend        || '';
  const langs   = techStack?.languages      || [];
  const infra   = techStack?.infrastructure || [];
  const hasKube = infra.some(item => item.includes('Kubernetes') || item.includes('AKS'));

  const GUARDS = {
    'governance/enterprise-constitution.md':                                       () => !levels.includes('enterprise'),
    '.github/instructions/azure-devops-pipelines.instructions.md':                 () => !devops.includes('Azure DevOps (ADO)'),
    '.github/instructions/github-actions.instructions.md':                         () => !devops.includes('GitHub Actions'),
    '.github/instructions/reactjs.instructions.md':                                () => fe !== 'React',
    '.github/instructions/nextjs.instructions.md':                                 () => fe !== 'Next.js',
    '.github/instructions/angular.instructions.md':                                () => fe !== 'Angular',
    '.github/instructions/nestjs.instructions.md':                                 () => be !== 'NestJS',
    '.github/instructions/aspnet-rest-apis.instructions.md':                       () => be !== 'ASP.NET Core',
    '.github/instructions/springboot.instructions.md':                             () => be !== 'Spring Boot',
    '.github/instructions/python.instructions.md':                                 () => !langs.includes('Python'),
    '.github/instructions/typescript-5-es2022.instructions.md':                    () => !langs.includes('TypeScript'),
    '.github/instructions/containerization-docker-best-practices.instructions.md': () => !infra.includes('Docker'),
    '.github/instructions/kubernetes-deployment-best-practices.instructions.md':   () => !hasKube,
    '.github/instructions/a11y.instructions.md':                                   () => !techStack?.useA11y,
    '.github/instructions/sonarqube.instructions.md':                              () => !(mcp?.tools || []).includes('sonarqube'),
  };

  const guard = GUARDS[path];
  return guard ? guard() : false;
}

// ─── generateAllFiles ────────────────────────────────────────────────────────
// Returns every file that should be pushed to GitHub:
//   1. All sdd-kit static files (prompts, instructions, templates, docs…)
//   2. Filtered by governance level selection
//   3. Wizard-generated files overwrite the defaults (project.md etc.)
export function generateAllFiles(formData) {
  // ── Step 1: start with all bundled kit files, filtered by selections ──────
  const files = {};
  for (const [path, content] of Object.entries(kitFiles)) {
    if (!shouldSkipFile(path, formData)) files[path] = content;
  }

  // ── Step 2: overlay wizard-generated files (project-specific content) ─────
  files['context/project.md']              = generateProjectMd(formData);
  files['context/tech-stack.md']           = generateTechStackMd(formData);
  files['context/constitution.md']         = generateConstitutionMd(formData);
  files['.github/copilot-instructions.md'] = generateCopilotInstructions(formData);

  const mcpJson = generateMcpJson(formData);
  if (mcpJson) files['.vscode/mcp.json'] = mcpJson;

  return files;
}

// ─── Helpers ─────────────────────────────────────────────────────────────────
function formatAgent(agentId) {
  const map = {
    'github-copilot': 'GitHub Copilot',
    'claude': 'Claude Code',
    'cursor': 'Cursor',
    'gemini': 'Gemini CLI',
  };
  return map[agentId] || agentId || 'GitHub Copilot';
}

function buildNamespace(governance, project) {
  const levels = governance?.levels || ['product'];
  const parts = [];
  if (levels.includes('enterprise')) parts.push('[ORG]');
  if (levels.includes('bu')) parts.push(governance?.buName || '[BU]');
  if (levels.includes('domain')) parts.push(governance?.domainName || '[DOMAIN]');
  parts.push(project?.name || '[PRODUCT]');
  return parts.join('.');
}
